name: Build, Test & Publish
on: [push, pull_request]
jobs:

  macos-test:
    runs-on: macos-latest
    strategy:
        matrix:
          python: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install tox
    - name: Test
      run: python -m tox -e py

  macos-build:
    needs: macos-test
    runs-on: macos-latest
    strategy:
        matrix:
          python: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install build dependencies
      run: python -m pip install build
    - name: Build
      run: python -m build --wheel
    - name: Store the built distribution
      uses: actions/upload-artifact@v2
      with:
        name: python-package-distributions
        path: dist
        retention-days: 4

  linux-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install tox
    - name: Test
      run: python -m tox -e py

  linux-build:
    needs: linux-test
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python: [3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install build dependencies
      run: python -m pip install build
    - name: Build
      run: python -m build --wheel
    - name: Store the built distribution
      uses: actions/upload-artifact@v2
      with:
        name: python-package-distributions
        path: dist
        retention-days: 4

  windows-test:
    runs-on: windows-latest
    strategy:
        matrix:
          python: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install tox
    - name: Test
      run: python -m tox -e py

  windows-build:
    needs: windows-test
    runs-on: windows-latest
    strategy:
        matrix:
          python: [3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install build dependencies
      run: python -m pip install build
    - name: Build
      run: python -m build --wheel
    - name: Store the built distribution
      uses: actions/upload-artifact@v2
      with:
        name: python-package-distributions
        path: dist
        retention-days: 4

  source-distribution:
    needs:
      - macos-build
      - linux-build
      - windows-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build source distribution
        run: python setup.py sdist
      - name: Store the source distribution
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist
          retention-days: 4

  publish:
    needs:
      - macos-build
      - linux-build
      - windows-build
      - source-distribution
    runs-on: ubuntu-latest
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v2
      with:
        name: python-package-distributions
        path: dist/
    - name: What will we publish?
      run: ls dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
